#!/usr/bin/env python3
"""
🧠 Proactive Memory Sync System
Lernt aus jedem Ereignis und aktualisiert Memory automatisch

Features:
- Triggert bei wichtigen Ereignissen (Deploys, Sales, Errors)
- Extrahiert Erkenntnisse automatisch
- Updated Memory ohne manuelles Eingreifen
- Historisiert wichtige Entscheidungen

Usage: python3 proactive_memory_sync.py [--sync] [--learn "Event text"]
"""

import subprocess
import json
import sys
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

# Config
MEMORY_DIR = Path("/home/clawbot/.openclaw/workspace/memory")
MEMORY_FILE = Path("/home/clawbot/.openclaw/workspace/MEMORY.md")
LEARNINGS_DIR = MEMORY_DIR / "learnings"
DECISIONS_DIR = MEMORY_DIR / "decisions"
DAILY_DIR = MEMORY_DIR / "daily"

# Trigger Patterns
TRIGGERS = {
    "deploy": {
        "patterns": [r"deployed", r"deploy.*success", r"vercel.*deploy", r"built.*successfully"],
        "category": "deployment",
        "importance": "medium"
    },
    "sale": {
        "patterns": [r"checkout\.session\.completed", r"sale", r"revenue", r"payment.*success"],
        "category": "revenue",
        "importance": "high"
    },
    "error": {
        "patterns": [r"error", r"failed", r"exception", r"❌", r"404", r"500"],
        "category": "error",
        "importance": "high"
    },
    "config_change": {
        "patterns": [r"stripe.*update", r"config.*change", r"token.*update", r"url.*change"],
        "category": "config",
        "importance": "high"
    },
    "lead": {
        "patterns": [r"lead", r"prospect", r"email.*sent", r"outreach"],
        "category": "sales",
        "importance": "medium"
    }
}

class ProactiveMemory:
    def __init__(self):
        self.memory_dir = MEMORY_DIR
        self.learnings_dir = LEARNINGS_DIR
        self.decisions_dir = DECISIONS_DIR
        self.daily_dir = DAILY_DIR
        
        # Ensure dirs exist
        for d in [self.learnings_dir, self.decisions_dir, self.daily_dir]:
            d.mkdir(parents=True, exist_ok=True)
    
    def should_remember(self, text: str) -> bool:
        """Prüft ob Text wichtig genug zum Erinnern ist"""
        text_lower = text.lower()
        for trigger_name, config in TRIGGERS.items():
            for pattern in config["patterns"]:
                if re.search(pattern, text_lower, re.IGNORECASE):
                    return True
        return False
    
    def extract_category(self, text: str) -> str:
        """Extrahiert Kategorie aus Text"""
        text_lower = text.lower()
        for trigger_name, config in TRIGGERS.items():
            for pattern in config["patterns"]:
                if re.search(pattern, text_lower, re.IGNORECASE):
                    return config["category"]
        return "general"
    
    def extract_importance(self, text: str) -> str:
        """Bestimmt Wichtigkeit"""
        text_lower = text.lower()
        for trigger_name, config in TRIGGERS.items():
            for pattern in config["patterns"]:
                if re.search(pattern, text_lower, re.IGNORECASE):
                    return config["importance"]
        return "low"
    
    def save_learning(self, text: str, category: str, importance: str) -> Path:
        """Speichert Lerner"""
        today = datetime.now().strftime("%Y-%m-%d")
        filename = self.learnings_dir / f"learning-{today}-{datetime.now().strftime('%H%M%S')}.md"
        
        content = f"""# Learning: {category.upper()}

**Timestamp:** {datetime.now().isoformat()}
**Importance:** {importance}
**Category:** {category}

## Event
```
{text}
```

## Extracted Insight
<!-- Hier vom Agenten auszufüllen -->

---

*Auto-generated by Proactive Memory System*
"""
        
        with open(filename, "w") as f:
            f.write(content)
        
        return filename
    
    def save_decision(self, text: str, context: str) -> Path:
        """Speichert Entscheidung"""
        today = datetime.now().strftime("%Y-%m-%d")
        filename = self.decisions_dir / f"decision-{today}-{datetime.now().strftime('%H%M%S')}.md"
        
        content = f"""# Decision

**Timestamp:** {datetime.now().isoformat()}
**Context:** {context}

## Decision
```
{text}
```

## Rationale
<!-- Hier vom Agenten auszufüllen -->

---

*Auto-generated by Proactive Memory System*
"""
        
        with open(filename, "w") as f:
            f.write(content)
        
        return filename
    
    def update_daily_log(self, text: str, category: str):
        """Updated Daily Log mit Event"""
        today = datetime.now().strftime("%Y-%m-%d")
        filename = self.daily_dir / f"{today}.md"
        
        if filename.exists():
            with open(filename) as f:
                content = f.read()
        else:
            content = f"# Daily Log: {today}\n\n"
        
        # Event hinzufügen
        timestamp = datetime.now().strftime("%H:%M")
        content += f"\n## [{timestamp}] {category.upper()}\n- {text}\n"
        
        with open(filename, "w") as f:
            f.write(content)
        
        return filename
    
    def update_main_memory(self, key: str, value: str, reason: str):
        """Updated MEMORY.md mit neuer Info"""
        if not MEMORY_FILE.exists():
            return None
        
        with open(MEMORY_FILE) as f:
            content = f.read()
        
        # Prüfen ob Key bereits existiert
        pattern = rf"(\*\*?{key}\*\*?:?\s*).*$"
        match = re.search(pattern, content, re.MULTILINE)
        
        if match:
            # Update existing
            old_line = match.group(0)
            new_line = f"{match.group(1)}{value}"
            content = content.replace(old_line, new_line)
        else:
            # Append to relevant section
            content += f"\n- **{key}:** {value}\n"
        
        with open(MEMORY_FILE, "w") as f:
            f.write(content)
        
        return MEMORY_FILE
    
    def learn_from_event(self, text: str) -> bool:
        """Hauptmethode: Lernt aus einem Ereignis"""
        if not self.should_remember(text):
            return False
        
        category = self.extract_category(text)
        importance = self.extract_importance(text)
        
        # 1. Learning speichern
        learning_file = self.save_learning(text, category, importance)
        
        # 2. Daily Log updaten
        daily_file = self.update_daily_log(text, category)
        
        # 3. Bei hohen Importance: Entscheidung/Config extrahieren
        if importance == "high":
            self.save_decision(text, f"Auto-extracted from {category} event")
        
        print(f"✅ Learned: [{category}] {text[:100]}...")
        return True
    
    def full_sync(self):
        """Vollständiger Memory Sync"""
        print("🧠 Running full memory sync...")
        
        # 1. Log-Files analysieren
        log_dir = Path("/home/clawbot/.openclaw/workspace/logs")
        if log_dir.exists():
            for log_file in log_dir.glob("*.log"):
                try:
                    with open(log_file) as f:
                        lines = f.readlines()
                    
                    # Letzte 100 Zeilen prüfen
                    for line in lines[-100:]:
                        self.learn_from_event(line.strip())
                except Exception as e:
                    print(f"⚠️ Error reading {log_file}: {e}")
        
        # 2. Recent Commits analysieren
        try:
            result = subprocess.run(
                ["git", "-C", str(MEMORY_DIR.parent), "log", "--oneline", "-10"],
                capture_output=True, text=True
            )
            if result.returncode == 0:
                for line in result.stdout.strip().split("\n"):
                    self.learn_from_event(line)
        except:
            pass
        
        print("✅ Memory sync complete")
        return True

def main():
    import argparse
    parser = argparse.ArgumentParser(description="Proactive Memory Sync")
    parser.add_argument("--learn", type=str, help="Learn from event text")
    parser.add_argument("--sync", action="store_true", help="Run full sync")
    parser.add_argument("--key", type=str, help="Key to update in memory")
    parser.add_argument("--value", type=str, help="Value for key")
    parser.add_argument("--reason", type=str, default="Auto-update", help="Reason for update")
    args = parser.parse_args()
    
    memory = ProactiveMemory()
    
    if args.learn:
        memory.learn_from_event(args.learn)
    elif args.key and args.value:
        memory.update_main_memory(args.key, args.value, args.reason)
    elif args.sync:
        memory.full_sync()
    else:
        print("Usage: proactive_memory_sync.py [--learn TEXT] [--sync] [--key KEY --value VALUE]")

if __name__ == "__main__":
    main()
