#!/usr/bin/env python3
"""
Sir HazeClaw Daily Summary Generator
Erstellt eine tägliche Zusammenfassung der Aktivitäten.

Usage:
    python3 daily_summary.py
    python3 daily_summary.py --date 2026-04-10
"""

import os
import sys
import json
from datetime import datetime, timedelta
from pathlib import Path

# Config
MEMORY_DIR = Path("/home/clawbot/.openclaw/workspace/memory")
CEO_DIR = Path("/home/clawbot/.openclaw/workspace/ceo")

def get_git_commits_today():
    """Holt Git Commits von heute."""
    import subprocess
    
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "--since='today 00:00'", "--format=%H %s"],
            cwd="/home/clawbot/.openclaw/workspace",
            capture_output=True,
            text=True
        )
        
        commits = []
        for line in result.stdout.strip().split('\n'):
            if line:
                parts = line.split(' ', 1)
                if len(parts) == 2:
                    commits.append({"hash": parts[0][:8], "msg": parts[1]})
        return commits
    except:
        return []

def get_memory_notes_today():
    """Holt Memory Notes von heute."""
    today = datetime.now().strftime("%Y-%m-%d")
    notes_file = MEMORY_DIR / f"{today}.md"
    
    if notes_file.exists():
        content = notes_file.read_text()
        return content
    return ""

def get_heartbeat_status():
    """Liest HEARTBEAT.md Status."""
    heartbeat = CEO_DIR / "HEARTBEAT.md"
    
    if heartbeat.exists():
        content = heartbeat.read_text()
        # Extract key info
        lines = content.split('\n')
        status_lines = [l for l in lines if '✅' in l or '❌' in l or '⚠️' in l][:10]
        return '\n'.join(status_lines)
    return ""

def get_backup_status():
    """Prüft Backup Status."""
    backup_dir = Path("/home/clawbot/.openclaw/backups")
    today = datetime.now().strftime("%Y%m%d")
    
    backups = list(backup_dir.glob(f"backup_{today}_*.tar.gz"))
    
    if backups:
        latest = max(backups, key=os.path.getmtime)
        size_mb = os.path.getsize(latest) / (1024*1024)
        return f"✅ Server Backup: {latest.name} ({size_mb:.1f}MB)"
    return "❌ Kein Server Backup heute"

def get_system_health():
    """Kurzer System Health Check."""
    import psutil
    
    disk = psutil.disk_usage('/')
    mem = psutil.virtual_memory()
    load = os.getloadavg()[0]
    
    checks = []
    
    # Disk
    if disk.percent < 90:
        checks.append(f"✅ Disk: {100-disk.percent:.0f}% free")
    else:
        checks.append(f"❌ Disk: {100-disk.percent:.0f}% free (LOW)")
    
    # Memory
    if mem.percent < 90:
        checks.append(f"✅ Memory: {100-mem.percent:.0f}% free")
    else:
        checks.append(f"❌ Memory: {100-mem.percent:.0f}% free (HIGH)")
    
    # Load
    if load < 4.0:
        checks.append(f"✅ Load: {load:.2f}")
    else:
        checks.append(f"❌ Load: {load:.2f} (HIGH)")
    
    return '\n'.join(checks)

def generate_summary():
    """Generiert täglichen Summary."""
    today = datetime.now().strftime("%Y-%m-%d")
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    
    summary = f"""# Daily Summary — {today}

Generated: {now}

---

## 🖥️ System Health

{get_system_health()}

---

## 💾 Backup Status

{get_backup_status()}

---

## 📊 Git Commits Today

"""
    
    commits = get_git_commits_today()
    if commits:
        for c in commits:
            summary += f"- `{c['hash']}` {c['msg']}\n"
    else:
        summary += "_No commits today_\n"
    
    summary += "\n---\n\n## 📝 Memory Notes Today\n\n"
    
    notes = get_memory_notes_today()
    if notes:
        summary += notes[:1000]  # First 1000 chars
    else:
        summary += "_No notes for today_\n"
    
    summary += "\n---\n\n## ❤️ HEARTBEAT Status\n\n"
    
    heartbeat = get_heartbeat_status()
    if heartbeat:
        summary += heartbeat
    else:
        summary += "_No heartbeat data_\n"
    
    summary += "\n\n---\n*Generated by Sir HazeClaw*\n"
    
    return summary

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description='Daily Summary Generator')
    parser.add_argument('--date', help='Date (YYYY-MM-DD)', default=None)
    parser.add_argument('--output', help='Output file', default=None)
    args = parser.parse_args()
    
    summary = generate_summary()
    
    if args.output:
        Path(args.output).write_text(summary)
        print(f"✅ Summary written to {args.output}")
    else:
        print(summary)

if __name__ == "__main__":
    main()