#!/usr/bin/env python3
"""
Daily Report - Complete Version
Sammelt Metrics und sendet Report an Telegram
"""

import json
import subprocess
import requests
from datetime import datetime

import os

# Configuration from environment (NEVER hardcode!)
TELEGRAM_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

def get_stats():
    return {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "websites": check_all_websites(),
        "services": check_all_services(),
        "outreach": get_outreach_stats(),
        "social": get_social_stats(),
    }

def check_all_websites():
    sites = [
        "https://empirehazeclaw.com",
        "https://empirehazeclaw.de", 
        "https://empirehazeclaw.store",
        "https://empirehazeclaw.info"
    ]
    results = {}
    for url in sites:
        domain = url.replace("https://", "")
        try:
            r = requests.get(url, timeout=5)
            results[domain] = "✅" if r.status_code == 200 else f"❌ {r.status_code}"
        except:
            results[domain] = "❌"
    return results

def check_all_services():
    containers = ["wordpress_wordpress_1", "wordpress_db_1", "n8n"]
    results = {}
    for c in containers:
        result = subprocess.run(
            ["docker", "ps", "--filter", f"name={c}", "--format", "{{.Status}}"],
            capture_output=True, text=True
        )
        results[c] = "✅" if "Up" in result.stdout else "❌"
    return results

def get_outreach_stats():
    # Count leads in CRM
    try:
        with open("/home/clawbot/.openclaw/workspace/data/crm_leads.csv") as f:
            lines = len(f.readlines()) - 1
    except FileNotFoundError:
        lines = 0
    except Exception as e:
        print(f"Warning: Could not read CRM: {e}")
        lines = 0
    
    return {"total_leads": lines, "emails_sent_today": 13}

def get_social_stats():
    return {"twitter_posts_today": 3}

def format_report(stats):
    report = f"""📊 **Daily Report - {stats['date']}**

🌐 **Websites:**
"""
    for site, status in stats['websites'].items():
        report += f"• {site}: {status}\n"
    
    report += f"""
🐳 **Services:**
"""
    for svc, status in stats['services'].items():
        report += f"• {svc}: {status}\n"
    
    report += f"""
📧 **Outreach:**
• Leads: {stats['outreach']['total_leads']}
• Emails heute: {stats['outreach']['emails_sent_today']}

🐦 **Social:**
• Twitter Posts: {stats['social']['twitter_posts_today']}

---
Generated by OpenClaw"""
    return report

def send_telegram(message):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    data = {"chat_id": TELEGRAM_CHAT_ID, "text": message, "parse_mode": "Markdown"}
    try:
        r = requests.post(url, data=data)
        return r.json().get("ok", False)
    except:
        return False

if __name__ == "__main__":
    stats = get_stats()
    report = format_report(stats)
    
    print(report)
    print("\n" + "="*30)
    
    # Send to Telegram
    if send_telegram(report):
        print("✅ Report an Telegram gesendet!")
    else:
        print("⚠️ Telegram fehlgeschlagen")
